#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
amixer sset Master unmute
amixer -c 1 sset Master unmute

bspc monitor -d I II III IV V VI VIII IX X

bspc config border_width	        2
bspc config window_gap          	8

bspc config focused_border_color	"#458588"
bspc config normal_border_color		"8EC07C"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
